name: MainWorkflow

on:
  workflow_run:
    workflows: ["subworkflow.yml"]
    types:
      - requested

jobs:
  main_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your main workflow steps go here
