name: Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      param1:
        description: 'Workflow A description'
        required: true
      param2:
        description: 'Workflow A description'
        required: false

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Step 1
        run: echo "Running Step 1"

      - name: Step 2
        run: echo "Running Step 2"
