name: GitHub Actions Multiple YAMLs Example

on:   
  workflow_dispatch:
   inputs:
      selectedYaml:
        description: 'Selected YAML files to run'
        required: true
      
          if [ ${{ github.event.inputs.selectedYaml }} == 'CalledWorkflow' ]; then
            echo "Running  CalledWorkflow files"
            # Add steps to run all YAML files

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Selected YAMLs
        run: |
          if [ ${{ github.event.inputs.selectedYaml }} == 'CalledWorkflow' ]; then
            echo "Running  CalledWorkflow files"
            # Add steps to run all YAML files
          elif [ ${{ github.event.inputs.selectedYaml }} == 'SubWorkflow' ]; then
            echo "Running SubWorkflow"
            # Add steps to run SubWorkflow
          else
            echo "Invalid YAML selection"
            exit 1
          fi
