name: GitHub Actions Multiple YAMLs Example

on:
  push:
    branches:
      - main
      
  workflow_dispatch:
   inputs:
      selectedYaml:
        description: 'Selected YAML files to run'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Selected YAMLs
        run: |
          if [ ${{ github.event.inputs.selectedYaml }} == 'all' ]; then
            echo "Running all YAML files"
            # Add steps to run all YAML files
          elif [ ${{ github.event.inputs.selectedYaml }} == 'yaml1' ]; then
            echo "Running YAML 1"
            # Add steps to run YAML 1
          elif [ ${{ github.event.inputs.selectedYaml }} == 'yaml2' ]; then
            echo "Running YAML 2"
            # Add steps to run YAML 2
          else
            echo "Invalid YAML selection"
            exit 1
          fi
