name: Sub Workflow

on:
  push:
    branches:
      - main

jobs:
  sub_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Your sub workflow steps go here

      - name: Trigger Main Workflow
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const mainWorkflow = async () => {
              const octokit = github.getOctokit(process.env.GITHUB_TOKEN);
              const { data: workflows } = await octokit.actions.listRepoWorkflows({
                owner: context.repo.owner,
                repo: context.repo.repo
              });

              const mainWorkflow = workflows.find(workflow => workflow.name === 'Main Workflow');
              if (!mainWorkflow) {
                throw new Error('Main Workflow not found');
              }

              await octokit.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: mainWorkflow.id,
                ref: context.ref,
                inputs: {
                  someInput: 'value' // Provide any necessary inputs
                }
              });
            };

            await mainWorkflow();
