name: GitHub Actions Multiple YAMLs Example

on:   
  workflow_dispatch:
   inputs:
      selectedYaml:
        description: 'Selected YAML files to run'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run Selected YAMLs
        run: |
          if [ ${{ github.event.inputs.selectedYaml }} == 'callerworkflow.yml' ]; then
            echo "Running all YAML files"
            # Add steps to run all YAML files
          elif [ ${{ github.event.inputs.selectedYaml }} == 'subworkflow.yml' ]; then
            echo "Running YAML 1"
            # Add steps to run YAML 1
          else
            echo "Invalid YAML selection"
            exit 1
          fi
