name: Multi-Workflow
on:
  workflow_dispatch:
    inputs:
      workflow_run:
        description: 'Choose the workflow run'
        required: true
        default: 'callerworkflow.yml'
jobs:
  run-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run workflow
        run: |
          case ${{ github.event.inputs.workflow_run }} in
          callerworkflow.yml)
            echo "Running Workflow 1"
            # Add steps specific to Workflow 1
            ;;
          subworkflow.yml)
            echo "Running Workflow 2"
            # Add steps specific to Workflow 2
            ;;
           subworkflow2.yml)
            echo "Running Workflow 3"
            # Add steps specific to Workflow 3
            ;;
          *)
            echo "Invalid workflow run specified"
            exit 1
            ;;
          esac
