name: workflow

on:
  workflow_run:
    workflows: ["callerworkflow.yml"]
    types:
      - completed      
jobs:
   build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2

