name: Workflow A

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Workflow B
        uses: ./.github/workflows/workflow-b
        with:
          checkbox-param: ${{ github.event.inputs.checkbox-param }}
